// LOCALHOST
// GET all sessions and games
### 
GET http://localhost:3000/sessions HTTP/1.1
###
GET http://localhost:3000/games HTTP/1.1

//GET session and game by id
### 
GET http://localhost:3000/sessions/682fa967698ba839ac821ca4 HTTP/1.1
### 
GET http://localhost:3000/sessions/682fa9b6698ba839ac821ca5 HTTP/1.1
### 
GET http://localhost:3000/sessions/682fa9c0698ba839ac821ca6 HTTP/1.1

### 
GET http://localhost:3000/games/682e9bdf4dd7fa13e4f39b2f HTTP/1.1
### 
GET http://localhost:3000/games/682fa88c698ba839ac821ca2 HTTP/1.1
### 
GET http://localhost:3000/games/682fa8b6698ba839ac821ca3 HTTP/1.1


// LOCAL POST
### Create/POST Game
POST http://localhost:3000/games HTTP/1.1
content-type: application/json

{
    "title": "Terraria",
    "platform": "Steam",
    "genre": "Open World",
    "multiplayer": "Yes",
    "developer": "Logic"
}

### Create/POST Session
POST http://localhost:3000/sessions HTTP/1.1
content-type: application/json

{
    "userId": "player2",
    "gameId": "682fda6c79e7bc4bb8da470a",
    "date": "11/21/2025",
    "startTime": "8:00pm",
    "duration": "3 hours",
    "players": ["Matt", "Billy"],
    "mode": "Survival",
    "platform": "Steam",
    "notes": "Continue hunting for supplies",
    "status": "planned"
}



### PUT Session
PUT http://localhost:3000/sessions/68268f88423b889d6d6a2269 HTTP/1.1
content-type: application/json

{
    "userId": "player2",
    "gameId": "682fda6c79e7bc4bb8da470a",
    "date": "11/21/2025",
    "startTime": "4:00pm",
    "duration": "6 hours",
    "players": ["Matt", "Billy"],
    "mode": "Survival",
    "platform": "Steam",
    "notes": "Continue hunting for supplies",
    "status": "cancelled"
}

### PUT Game
PUT http://localhost:3000/games/68268f88423b889d6d6a2269 HTTP/1.1
content-type: application/json

{
    "title": "Terraria",
    "platform": "Steam",
    "genre": "Sandbox",
    "multiplayer": "Yes",
    "developer": "Re-Logic"
}


### DELETE Session
DELETE http://localhost:3000/sessions/682fdb64776b03d3f5e10fa9 HTTP/1.1

### DELETE Game
DELETE http://localhost:3000/games/682fda6c79e7bc4bb8da470a HTTP/1.1



// PRODUCTION DEPLOY
### Get all sessions
GET https://cse-341-project-2-2548.onrender.com/sessions

### Get all games
GET https://cse-341-project-2-2548.onrender.com/games


### Get session by id
GET https://cse-341-project-2-2548.onrender.com/sessions/682fa967698ba839ac821ca4

### Get games by id
GET https://cse-341-project-2-2548.onrender.com/games/682e9bdf4dd7fa13e4f39b2f 


### Create/POST session
POST https://cse-341-project-2-2548.onrender.com/sessions HTTP/1.1
content-type: application/json

{
    "userId": "player2",
    "gameId": "682fe6360da8fc4f6ed246bb",
    "date": "11/21/2025",
    "startTime": "8:00pm",
    "duration": "3 hours",
    "players": ["Matt, Billy"],
    "mode": "Survival",
    "platform": "Steam",
    "notes": "Continue hunting for supplies",
    "status": "Planned"
}

### Create/POST game
POST https://cse-341-project-2-2548.onrender.com/games/ HTTP/1.1
content-type: application/json

{
    "title": "Terraria",
    "platform": "Steam",
    "genre": "Open World",
    "multiplayer": "Yes",
    "developer": "Logic"
}


### PUT session
PUT https://cse-341-project-2-2548.onrender.com/sessions/682fe2da4e9ffbe0bc7879a7 HTTP/1.1
content-type: application/json

{
    "userId": "player2",
    "gameId": "682fe2a24e9ffbe0bc7879a6",
    "date": "11/21/2025",
    "startTime": "4:00pm",
    "duration": "6 hours",
    "players": ["Matt, Billy"],
    "mode": "Survival",
    "platform": "Steam",
    "notes": "Continue hunting for supplies",
    "status": "Pending"
}

### PUT game
PUT https://cse-341-project-2-2548.onrender.com/games/682fe2a24e9ffbe0bc7879a6 HTTP/1.1
content-type: application/json

{
    "title": "Terraria",
    "platform": "Steam",
    "genre": "Sandbox",
    "multiplayer": "Yes",
    "developer": "Re-Logic"
}


### DELETE Session
DELETE https://cse-341-project-2-2548.onrender.com/sessions/682fe2da4e9ffbe0bc7879a7 HTTP/1.1

### DELETE Game
DELETE https://cse-341-project-2-2548.onrender.com/games/682fe2a24e9ffbe0bc7879a6 HTTP/1.1